### ISSUE TITLE
/ by zero

### ISSUE THREAD

**Issue by google-mirror** [fornwall/jelf#21]
![QQ拼音截图20230907163831](https://github.com/fornwall/jelf/assets/70927995/9cf063f2-40de-443f-a7f4-6901b34ed193)

```
Exception in thread "main" java.lang.ArithmeticException: / by zero
	at net.fornwall.jelf.ElfDynamicStructure.<init>(ElfDynamicStructure.java:315)
	at net.fornwall.jelf.ElfSegment$3.computeValue(ElfSegment.java:153)
	at net.fornwall.jelf.ElfSegment$3.computeValue(ElfSegment.java:150)
	at net.fornwall.jelf.MemoizedObject.getValue(MemoizedObject.java:21)
	at net.fornwall.jelf.ElfSegment.getDynamicStructure(ElfSegment.java:255)
```

**Comment by google-mirror** [comment]
[libc.zip](https://github.com/fornwall/jelf/files/12546686/libc.zip)
